### ISSUE TITLE
Wrong documentation about start script

### ISSUE THREAD

**Issue by safakadir** [cyclic-software/starter-nestjs#3]
I see the start script in package.json file is modified as "node dist/main" since cyclic uses "npm run start" to run the production application. But in the README, it says to use "npm run start" for development.

**Comment by fcole90** [comment]
Indeed it might make sense to change it as you suggest :thinking:

**Comment by seekayel** [comment]
Should be fixed by PR #5

**Comment by vaidyahimanshu502** [comment]
Check package.json script: Ensure that the start script in the package.json file is updated to the appropriate command for running the application during development. It should be set to npm run start rather than node dist/main.

**Comment by seekayel** [comment]
@vaidyahimanshu502 are you saying that the fix didn't work? Are there more improvements to make?

**Comment by vaidyahimanshu502** [comment]
See you have written 

# development - watch mode
$ npm run start:dev

# development - debug & watch mode
$ npm run start:debug

# production mode
$ npm run start    these commands for dev, prod and test these wouldn't be same.

Ex.  
For dev : npm run dev or in package.json if you are using modem then you can write 
"Dev":"nodemon xyz.js".

For production : npm run start or in package.json
Write
"start":"node xyz.js"
